collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: 'cat'
    label: 'Cats'
    folder: 'src/content/cat'
    create: true
    identifier_field: 'name'
    fields:
      - label: 'Name'
        required: true
        name: 'name'
        widget: 'string'
      - label: 'Type'
        required: true
        name: 'type'
        widget: 'hidden'
        default: 'cat'
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        default: '{{now}}'
      - label: 'Age'
        required: false
        name: 'age'
        widget: 'number'
      - label: 'Size'
        required: false
        name: 'size'
        widget: 'select'
        options:
          - { label: 'Small', value: 'small' }
          - { label: 'Medium', value: 'medium' }
          - { label: 'Large', value: 'large' }
      - label: 'Images'
        required: false
        name: "images"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
      - label: "Personality Traits"
        required: false
        name: "personality_traits"
        widget: "relation"
        multiple: true
        collection: "personality_traits"
        search_fields: ["name"]
        value_field: "name"
      - label: "Health Status"
        required: false
        name: "health_status"
        widget: "relation"
        multiple: true
        collection: "health_status"
        search_fields: ["name"]
        value_field: "name"
      - label: 'Breed'
        required: false
        name: 'breed'
        widget: 'string'
      - label: 'Bio'
        required: false
        name: 'bio'
        widget: 'markdown'
  - name: 'dog'
    label: 'Dogs'
    folder: 'src/content/dog'
    create: true
    identifier_field: 'name'
    fields:
      - label: 'Name'
        required: true
        name: 'name'
        widget: 'string'
      - label: 'Type'
        required: true
        name: 'type'
        widget: 'hidden'
        default: 'dog'
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        default: '{{now}}'
      - label: 'Age'
        required: false
        name: 'age'
        widget: 'number'
      - label: 'Size'
        required: false
        name: 'size'
        widget: 'select'
        options:
          - { label: 'Small', value: 'small' }
          - { label: 'Medium', value: 'medium' }
          - { label: 'Large', value: 'large' }
      - label: 'Images'
        required: false
        name: "images"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
      - label: "Personality Traits"
        required: false
        name: "personality_traits"
        widget: "relation"
        multiple: true
        collection: "personality_traits"
        search_fields: ["name"]
        value_field: "name"
      - label: "Health Status"
        required: false
        name: "health_status"
        widget: "relation"
        multiple: true
        collection: "health_status"
        search_fields: ["name"]
        value_field: "name"
      - label: 'Breed'
        required: false
        name: 'breed'
        widget: 'string'
      - label: 'Bio'
        required: false
        name: 'bio'
        widget: 'markdown'
  - name: 'personality_traits'
    label: 'Personality traits'
    folder: 'src/content/personality_traits'
    identifier_field: 'name'
    create: true
    fields: 
      - label: 'Name'
        name: 'name'
        widget: 'string'
  - name: 'health_status'
    label: 'Health Status'
    folder: 'src/content/health_status'
    identifier_field: 'name'
    create: true
    fields: 
      - label: 'Name'
        name: 'name'
        widget: 'string'
  - name: "static"
    label: "Static"
    identifier_field: 'name'
    files:
      - label: "Footer"
        name: "footer"
        file: "src/content/static/footer.md"
        fields:
          - { label: "LinkedIn", name: "linkedIn", widget: "string", hint: "Url to LinkedIn page, leave empty to skip", required: false }
          - { label: "Facebook", name: "facebook", widget: "string", hint: "Url to Facebook page, leave empty to skip", required: false }
          - { label: "Twitter", name: "twitter", widget: "string", hint: "Url to Twitter page, leave empty to skip", required: false }
          - { label: "Image", name: "image", widget: "image", hint: "Image to display in footer, leave empty to skip", required: false, choose_url: true }
          - { label: "Body", name: "body", widget: "markdown" }
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
local_backend: 
    url: http://localhost:8081/api/v1
backend:
  name: git-gateway
